---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: harness-blue-green-test
    heritage: {{.Release.Service | quote}}
    release: {{.Release.Name | quote}}
    chart: {{ .Chart.Name }}
  annotations:
    "service-version": {{ .Chart.AppVersion | quote }}
  name: harness-blue-green-test
spec:
  selector:
      matchLabels:
        app: harness-blue-green-test
  template:
    metadata:
      labels:
        heritage: {{.Release.Service | quote}}
        release: {{.Release.Name | quote}}
        chart: {{ .Chart.Name }}
        app: harness-blue-green-test
    spec:
      serviceAccountName: harness-blue-green-test
      containers:
      - name: harness-blue-green-test
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 10
          periodSeconds: 30
        image: {{required ".Values.image.source is required" .Values.image.source }}
        ports:
        - containerPort: 8080
          protocol: TCP
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.image.resources | indent 10 }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
