{{- if .Values.ingress.class }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: harness-blue-green-test
  labels:
    app: harness-blue-green-test
    heritage: {{.Release.Service | quote}}
    release: {{.Release.Name | quote}}
    chart: {{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class | quote}}
    nginx.ingress.kubernetes.io/secure-backends: "false"
    {{- if eq .Values.ingress.affinity "cookie" }}
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    {{- else if eq .Values.ingress.affinity "client-ip"}}
    nginx.ingress.kubernetes.io/upstream-hash-by: "$the_real_ip"
    {{- else if ne .Values.ingress.affinity ""}}
    {{ required "invalid value for .Values.ingress.affinity" "" }}
    {{- end }}
spec:
  tls:
  - hosts:
    - {{ required ".Values.ingress.fqdn is required if .Values.ingress.class is non-empty" .Values.ingress.fqdn | quote}}
    {{- if .Values.ingress.certSecretName }}
    secretName: {{ .Values.ingress.certSecretName | quote}}
    {{- end }}
  rules:
  - host: {{ required ".Values.ingress.fqdn is required if .Values.ingress.class is non-empty" .Values.ingress.fqdn | quote}}
    http:
      paths:
      - backend:
          serviceName: harness-blue-green-test
          servicePort: 8080
  - host: {{ required ".Values.ingress.fqdnStage is required if .Values.ingress.class is non-empty" .Values.ingress.fqdnStage | quote}}
    http:
      paths:
      - backend:
          serviceName: harness-blue-green-test-staged
          servicePort: 8080
{{- end }}
