apiVersion: v1
kind: Service
metadata:
  labels:
    app: harness-blue-green-test
    heritage: {{.Release.Service | quote}}
    release: {{.Release.Name | quote}}
    chart: {{ .Chart.Name }}
  annotations:
    prometheus.io/scrape: "true"
    harness.io/stage-service: "true"
  name: harness-blue-green-test-staged
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: https
  selector:
    app: harness-blue-green-test
  sessionAffinity: None
  type: ClusterIP
