apiVersion: v1
kind: ServiceAccount
metadata:
  name: hanress-blue-green-test
  labels:
    app: hanress-blue-green-test
    heritage: {{.Release.Service | quote}}
    release: {{.Release.Name | quote}}
    chart: {{ .Chart.Name }}
